# -*- coding:utf-8 -*-
from mako import runtime, filters, cache
UNDEFINED = runtime.UNDEFINED
STOP_RENDERING = runtime.STOP_RENDERING
__M_dict_builtin = dict
__M_locals_builtin = locals
_magic_number = 10
_modified_time = 1450802316.709872
_enable_loop = True
_template_filename = '/home/cpett/summer_project/homepage/templates/base2.htm'
_template_uri = '/homepage/templates/base2.htm'
_source_encoding = 'utf-8'
import os, os.path, re
_exports = []


from django_mako_plus.controller import static_files 

def render_body(context,**pageargs):
    __M_caller = context.caller_stack._push_frame()
    try:
        __M_locals = __M_dict_builtin(pageargs=pageargs)
        request = context.get('request', UNDEFINED)
        STATIC_URL = context.get('STATIC_URL', UNDEFINED)
        self = context.get('self', UNDEFINED)
        __M_writer = context.writer()
        __M_writer('\n')
        __M_writer('\n')
        static_renderer = static_files.StaticRenderer(self) 
        
        __M_locals_builtin_stored = __M_locals_builtin()
        __M_locals.update(__M_dict_builtin([(__M_key, __M_locals_builtin_stored[__M_key]) for __M_key in ['static_renderer'] if __M_key in __M_locals_builtin_stored]))
        __M_writer('\n\n<!DOCTYPE html>\n<html lang="en">\n<html>\n  <meta charset="UTF-8">\n  <head>\n    <meta name="description" content="Finance Something">\n    <meta name="keywords" content="data visualization, finance, money, personl">\n    <meta charset="utf-8">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <meta name="description" content="">\n    <meta name="author" content="">\n\n    <title>Finance Something</title>\n    \n')
        __M_writer('    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>\n    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>\n    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">\n    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">\n    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>\n    <!--<script src="')
        __M_writer(str(STATIC_URL))
        __M_writer('users/scripts/script.js/"></script>-->\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/jquery.form.js"></script>\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/jquery.loadmodal.js"></script>\n    <script src="')
        __M_writer(str(STATIC_URL))
        __M_writer('homepage/scripts/signup.js/"></script>\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/scripts/base.js"></script>\n    <!-- Bootstrap Core CSS -->\n    <link src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/styles/bootstrap.min.css" rel="stylesheet">\n\n    <!-- Custom CSS -->\n    <link src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/styles/landing-page.css" rel="stylesheet">\n\n    <!-- Custom Fonts -->\n    <link src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/styles/font-awesome.min.css" rel="stylesheet" type="text/css">\n    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8"></script>\n\n    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\n    <!-- WARNING: Respond.js doesn\'t work if you view the page via file:// -->\n    <!--[if lt IE 9]>\n        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>\n        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>\n    <![endif]-->\n')
        __M_writer('    ')
        __M_writer(str( static_renderer.get_template_css(request, context)  ))
        __M_writer('\n\n</head>\n\n<body>\n\n    <!-- Navigation -->\n    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">\n        <div class="container topnav">\n            <!-- Brand and toggle get grouped for better mobile display -->\n            <div class="navbar-header">\n                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">\n                    <span class="sr-only">Toggle navigation</span>\n                    <span class="icon-bar"></span>\n                    <span class="icon-bar"></span>\n                    <span class="icon-bar"></span>\n                </button>\n                <!--<a class="navbar-brand topnav" href="#">Login</a> -->\n            </div>\n            <!-- Collect the nav links, forms, and other content for toggling -->\n            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">\n                <ul class="nav navbar-nav navar-left">\n')
        if request.user.is_authenticated():
            __M_writer('                    <div class="list-inline">\n                        <li><a href="/users/account/"><button class="btn btn-success btn-lg">My Account</button></a></li>\n                        <li><a href="/homepage/logout/"><button class="btn btn-primary btn-lg">Log Out</button></a></li>\n                    </div>\n')
        else:
            __M_writer('                    <div class="list-inline">\n                        <li><button id="show_login_dialog" class="btn btn-success btn-lg">Login</button></li>\n                        <li><a href="/homepage/signup.create"><button class="btn btn-primary btn-lg">Sign Up</button></a></li>\n                    </div>\n')
        __M_writer('                </ul>\n                <ul class="nav navbar-nav navbar-right">\n')
        if request.user.is_authenticated():
            __M_writer('                    <li><a>Welcome, ')
            __M_writer(str( request.user.get_full_name() ))
            __M_writer(' </a> </li>\n                    <li>\n                        <a href="/account/account">Accounts</a>\n                    </li>\n                    <li>\n                        <a href="/transaction/transaction/">Transactions</a>\n                    </li>\n                    <li>\n                        <a href="/dashboard/dashboard">Dashboard</a>\n                    </li>\n')
        else:
            __M_writer('                    <li>\n                        <a href="#about">About</a>\n                    </li>\n                    <li>\n                        <a href="#services">Services</a>\n                    </li>\n                    <li>\n                        <a href="#contact">Contact</a>\n                    </li>\n')
        __M_writer('                </ul>\n            </div>\n            <!-- /.navbar-collapse -->\n        </div>\n        <!-- /.container -->\n    </nav>\n\n        <!-- Modal Login-->\n          <div class="modal fade" id="login_dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">\n            <div class="modal-dialog">\n              <div class="modal-content">\n                <div class="modal-header">\n                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>\n                  <h4 class="modal-title" id="myModalLabel">Please Login</h4>\n                </div>\n                <div class="modal-body">\n                  ...\n                </div>\n                  <!--\n                    <div class="modal-footer">\n                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>\n                      <button type="button" class="btn btn-warning">Save changes</button>\n                    </div>\n                  -->\n              </div>\n            </div>\n          </div>\n\n    <!-- Header -->\n    <a name="about"></a>\n    <div class="intro-header">\n        <div class="container">\n\n            <div class="row">\n                <div class="col-lg-12">\n                    <div class="intro-message">\n                        <h1>My Finances</h1>\n                        <h3>Personal Finances</h3>\n                        <hr class="intro-divider">\n\n\n')
        if request.user.has_perm('add_logentry'):                        
            __M_writer('                            <ul class="list-inline intro-social-buttons">\n                                <li>\n                                    <a href="/users/users/" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Users</span></a>\n                                </li>\n                                <li>\n                                    <a href="/account/account" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Accounts</span></a>\n                                </li>\n                                <li>\n                                    <a href="/transaction/transaction" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Transactions</span></a>\n                                </li>\n                                <li>\n                                    <a href="/dashboard/dashboard" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Dashboard</span></a>\n                                </li>\n                            </ul>\n')
        elif request.user.is_authenticated():
            __M_writer('                            <ul class="list-inline intro-social-buttons">\n                                <li>\n                                    <a href="/account/account" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Accounts</span></a>\n                                </li>\n                                <li>\n                                    <a href="/transaction/transaction" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Transactions</span></a>\n                                </li>\n                                <li>\n                                    <a href="/dashboard/dashboard" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Dashboard</span></a>\n                                </li>\n                            </ul>\n')
        else:
            __M_writer('                            <ul class="list-inline intro-social-buttons">\n                                <li>\n                                    <a href="https://www.linkedin.com/in/codybpettit" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>\n                                </li>\n                                <li>\n                                    <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Lorem</span></a>\n                                </li>\n                                <li>\n                                    <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Ipsum</span></a>\n                                </li>\n                            </ul>\n')
        __M_writer('                    </div>\n                </div>\n            </div>\n\n        </div>\n        <!-- /.container -->\n\n    </div>\n    <!-- /.intro-header -->\n\n    <!-- Page Content -->\n\n    <a  name="services"></a>\n    <div class="content-section-a">\n\n        <div class="container">\n            <div class="row">\n                <div class="col-lg-5 col-sm-6">\n                    <hr class="section-heading-spacer">\n                    <div class="clearfix"></div>\n                    <h2 class="section-heading">A Bit About<br>This Site</h2>\n                    <p class="lead">I started building this site during my free time after an intro to web dev class. I wanted to practice more with <a href="https://github.com/doconix/django-mako-plus">Django-Mako-Plus</a> and <a href="http://d3js.org/">d3.js</a>.<br>\n                    If you want to look around, feel free to create a profile, or ask me for the test account credentials.<br>\n                    This is very much a work-in-progress, but feel free to poke around and please give me feed back!</p>\n                </div>\n                <div class="col-lg-5 col-lg-offset-2 col-sm-6">\n                    <img class="img-responsive" src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/ipad.png" alt="">\n                </div>\n            </div>\n\n        </div>\n        <!-- /.container -->\n\n    </div>\n    <!-- /.content-section-a -->\n\n    <div class="content-section-b">\n\n        <div class="container">\n\n            <div class="row">\n                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">\n                    <hr class="section-heading-spacer">\n                    <div class="clearfix"></div>\n                    <h2 class="section-heading">A Bit About<br>Me</h2>\n                    <p class="lead">My name is Cody Pettit. I am currently working toward a Masters of Information Systems Management at BYU. I have a passion for technology, and I am fasinated by data security and the trends within that industry.<br><br>When I\'m not studying or working, I am probably working on projects like this, watching a movie with my beautiful wife, Sidney, or longboarding in the canyon with friends.<br><br>Sidney and I love to travel and have adventures! I lived in Romania for two years, and we have been to Jamaica, Grand Cayman, and Cozumel. We are planning a trip to Europe after we graduate--We want to see as much of the world as possible!<br><br>Please feel free to reach out to me via email or LinkedIn.</p>\n                </div>\n                <div class="col-lg-5 col-sm-pull-6  col-sm-6">\n                    <img class="img-responsive" src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/me.jpg" alt="">\n                </div>\n            </div>\n\n        </div>\n        <!-- /.container -->\n\n    </div>\n    <!-- /.content-section-b -->\n\n    <div class="content-section-a">\n\n        <div class="container">\n\n            <div class="row">\n                <div class="col-lg-5 col-sm-6">\n                    <hr class="section-heading-spacer">\n                    <div class="clearfix"></div>\n                    <h2 class="section-heading">A Bit About<br>The Technology</h2>\n                    <p class="lead">I used <a href="https://github.com/doconix/django-mako-plus">Django-Mako-Plus</a> (DMP) to develop this site. The main purpose of this site was to practice with DMP and learn data visualization with <a href="http://d3js.org/">d3.js</a>. This site also features a PostegreSQL database, Bootstrap, and a few JavaScript libraries. Also, the stock photos are from <a href="http://deathtothestockphoto.com/">Death to the Stock Photo</a?</p>\n                </div>\n                <div class="col-lg-5 col-lg-offset-2 col-sm-6">\n                    <img class="img-responsive" src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/music.png" alt="">\n                </div>\n            </div>\n\n        </div>\n        <!-- /.container -->\n\n    </div>\n    <!-- /.content-section-a -->\n\n    <a  name="contact"></a>\n    <div class="banner">\n\n        <div class="container">\n\n            <div class="row">\n                <div class="col-lg-6">\n                    <h2>Summer 2015 Project</h2>\n                </div>\n                <div class="col-lg-6">\n                    <ul class="list-inline banner-social-buttons">\n                        <li>\n                            <a href="https://github.com/doconix/django-mako-plus" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">DMP</span></a>\n                        </li>\n                        <li>\n                            <a href="https://github.com/cpett" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>\n                        </li>\n                        <li>\n                            <a href="https://www.linkedin.com/in/codybpettit" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>\n                        </li>\n                    </ul>\n                </div>\n            </div>\n\n        </div>\n        <!-- /.container -->\n\n    </div>\n    <!-- /.banner -->\n\n    <!-- Footer -->\n    <footer>\n        <div class="container">\n            <div class="row">\n                <div class="col-lg-12">\n                    <ul class="list-inline">\n                        <li>\n                            <a href="#">Home</a>\n                        </li>\n                        <li class="footer-menu-divider">&sdot;</li>\n                        <li>\n                            <a href="#about">About</a>\n                        </li>\n                        <li class="footer-menu-divider">&sdot;</li>\n                        <li>\n                            <a href="#services">Services</a>\n                        </li>\n                        <li class="footer-menu-divider">&sdot;</li>\n                        <li>\n                            <a href="#contact">Contact</a>\n                        </li>\n                    </ul>\n                    <p class="copyright text-muted small">Est odio ac at nulla, litora proin aenean risus nulla soluta</p>\n                </div>\n            </div>\n        </div>\n    </footer>\n\n    <!-- jQuery \n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/scripts/jquery.js"></script>\n    -->     \n    <!-- Bootstrap Core JavaScript -->\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/scripts/bootstrap.min.js"></script>\n\n</body>\n\n</html>\n')
        return ''
    finally:
        context.caller_stack._pop_frame()


"""
__M_BEGIN_METADATA
{"source_encoding": "utf-8", "uri": "/homepage/templates/base2.htm", "line_map": {"17": 4, "19": 0, "27": 2, "28": 4, "29": 5, "33": 5, "34": 23, "35": 28, "36": 28, "37": 29, "38": 29, "39": 30, "40": 30, "41": 31, "42": 31, "43": 32, "44": 32, "45": 34, "46": 34, "47": 37, "48": 37, "49": 40, "50": 40, "51": 51, "52": 51, "53": 51, "54": 73, "55": 74, "56": 78, "57": 79, "58": 84, "59": 86, "60": 87, "61": 87, "62": 87, "63": 97, "64": 98, "65": 108, "66": 149, "67": 150, "68": 164, "69": 165, "70": 176, "71": 177, "72": 189, "73": 215, "74": 215, "75": 237, "76": 237, "77": 259, "78": 259, "79": 328, "80": 328, "81": 331, "82": 331, "88": 82}, "filename": "/home/cpett/summer_project/homepage/templates/base2.htm"}
__M_END_METADATA
"""
