# -*- coding:utf-8 -*-
from mako import runtime, filters, cache
UNDEFINED = runtime.UNDEFINED
STOP_RENDERING = runtime.STOP_RENDERING
__M_dict_builtin = dict
__M_locals_builtin = locals
_magic_number = 10
_modified_time = 1450908882.115273
_enable_loop = True
_template_filename = 'C:\\Python34\\Lib\\site-packages\\django\\bin\\summer_project/homepage/templates/base2.htm'
_template_uri = '/homepage/templates/base2.htm'
_source_encoding = 'utf-8'
import os, os.path, re
_exports = []


from django_mako_plus.controller import static_files 

def render_body(context,**pageargs):
    __M_caller = context.caller_stack._push_frame()
    try:
        __M_locals = __M_dict_builtin(pageargs=pageargs)
        STATIC_URL = context.get('STATIC_URL', UNDEFINED)
        self = context.get('self', UNDEFINED)
        request = context.get('request', UNDEFINED)
        __M_writer = context.writer()
        __M_writer('\r\n')
        __M_writer('\r\n')
        static_renderer = static_files.StaticRenderer(self) 
        
        __M_locals_builtin_stored = __M_locals_builtin()
        __M_locals.update(__M_dict_builtin([(__M_key, __M_locals_builtin_stored[__M_key]) for __M_key in ['static_renderer'] if __M_key in __M_locals_builtin_stored]))
        __M_writer('\r\n\r\n<!DOCTYPE html>\r\n<html lang="en">\r\n<html>\r\n  <meta charset="UTF-8">\r\n  <head>\r\n    <meta name="description" content="Finance Something">\r\n    <meta name="keywords" content="data visualization, finance, money, personl">\r\n    <meta charset="utf-8">\r\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\r\n    <meta name="viewport" content="width=device-width, initial-scale=1">\r\n    <meta name="description" content="">\r\n    <meta name="author" content="">\r\n\r\n    <title>Finance Something</title>\r\n    \r\n')
        __M_writer('    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>\r\n    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>\r\n    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">\r\n    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">\r\n    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>\r\n    <!--<script src="')
        __M_writer(str(STATIC_URL))
        __M_writer('users/scripts/script.js/"></script>-->\r\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/jquery.form.js"></script>\r\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/jquery.loadmodal.js"></script>\r\n    <script src="')
        __M_writer(str(STATIC_URL))
        __M_writer('homepage/scripts/signup.js/"></script>\r\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/scripts/base.js"></script>\r\n    <!-- Bootstrap Core CSS -->\r\n    <link src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/styles/bootstrap.min.css" rel="stylesheet">\r\n\r\n    <!-- Custom CSS -->\r\n    <link src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/styles/landing-page.css" rel="stylesheet">\r\n\r\n    <!-- Custom Fonts -->\r\n    <link src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/styles/font-awesome.min.css" rel="stylesheet" type="text/css">\r\n    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">\r\n    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js" charset="utf-8"></script>\r\n\r\n    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n    <!-- WARNING: Respond.js doesn\'t work if you view the page via file:// -->\r\n    <!--[if lt IE 9]>\r\n        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>\r\n        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>\r\n    <![endif]-->\r\n')
        __M_writer('    ')
        __M_writer(str( static_renderer.get_template_css(request, context)  ))
        __M_writer('\r\n\r\n</head>\r\n\r\n<body>\r\n\r\n    <!-- Navigation -->\r\n    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">\r\n        <div class="container topnav">\r\n            <!-- Brand and toggle get grouped for better mobile display -->\r\n            <div class="navbar-header">\r\n                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">\r\n                    <span class="sr-only">Toggle navigation</span>\r\n                    <span class="icon-bar"></span>\r\n                    <span class="icon-bar"></span>\r\n                    <span class="icon-bar"></span>\r\n                </button>\r\n                <!--<a class="navbar-brand topnav" href="#">Login</a> -->\r\n            </div>\r\n            <!-- Collect the nav links, forms, and other content for toggling -->\r\n            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">\r\n                <ul class="nav navbar-nav navar-left">\r\n')
        if request.user.is_authenticated():
            __M_writer('                    <div class="list-inline">\r\n                        <li><a href="/users/account/"><button class="btn btn-success btn-md btntop">My Account</button></a></li>\r\n                        <li><a href="/homepage/logout/"><button class="btn btn-primary btn-md btntop">Log Out</button></a></li>\r\n                    </div>\r\n')
        else:
            __M_writer('                    <div class="list-inline">\r\n                        <li><button id="show_login_dialog" class="btn btn-success btn-md btntop">Login</button></li>\r\n                        <li><a href="/homepage/signup.create"><button class="btn btn-primary btn-md btntop">Sign Up</button></a></li>\r\n                    </div>\r\n')
        __M_writer('                </ul>\r\n                <ul class="nav navbar-nav navbar-right">\r\n')
        if request.user.is_authenticated():
            __M_writer('                    <li><a>Welcome, ')
            __M_writer(str( request.user.get_full_name() ))
            __M_writer(' </a> </li>\r\n                    <li>\r\n                        <a href="/account/account">Accounts</a>\r\n                    </li>\r\n                    <li>\r\n                        <a href="/transaction/transaction/">Transactions</a>\r\n                    </li>\r\n                    <li>\r\n                        <a href="/dashboard/dashboard">Dashboard</a>\r\n                    </li>\r\n')
        __M_writer('                </ul>\r\n            </div>\r\n            <!-- /.navbar-collapse -->\r\n        </div>\r\n        <!-- /.container -->\r\n    </nav>\r\n\r\n        <!-- Modal Login-->\r\n          <div class="modal fade" id="login_dialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">\r\n            <div class="modal-dialog">\r\n              <div class="modal-content">\r\n                <div class="modal-header">\r\n                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>\r\n                  <h4 class="modal-title" id="myModalLabel">Please Login</h4>\r\n                </div>\r\n                <div class="modal-body">\r\n                  ...\r\n                </div>\r\n                  <!--\r\n                    <div class="modal-footer">\r\n                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>\r\n                      <button type="button" class="btn btn-warning">Save changes</button>\r\n                    </div>\r\n                  -->\r\n              </div>\r\n            </div>\r\n          </div>\r\n\r\n    <!-- Header -->\r\n    <a name="about"></a>\r\n    <div class="intro-header">\r\n        <div class="container">\r\n\r\n            <div class="row">\r\n                <div class="col-lg-12">\r\n                    <div class="intro-message">\r\n                        <h1>My Finances</h1>\r\n                        <h3>Personal Finances</h3>\r\n                        <hr class="intro-divider">\r\n\r\n\r\n')
        if request.user.has_perm('add_logentry'):                        
            __M_writer('                            <ul class="list-inline intro-social-buttons">\r\n                                <li>\r\n                                    <a href="/users/users/" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Users</span></a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href="/account/account" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Accounts</span></a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href="/transaction/transaction" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Transactions</span></a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href="/dashboard/dashboard" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Dashboard</span></a>\r\n                                </li>\r\n                            </ul>\r\n')
        elif request.user.is_authenticated():
            __M_writer('                            <ul class="list-inline intro-social-buttons">\r\n                                <li>\r\n                                    <a href="/account/account" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Accounts</span></a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href="/transaction/transaction" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Transactions</span></a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href="/dashboard/dashboard" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Dashboard</span></a>\r\n                                </li>\r\n                            </ul>\r\n')
        else:
            __M_writer('                            <ul class="list-inline intro-social-buttons">\r\n                                <li>\r\n                                    <a href="https://www.linkedin.com/in/codybpettit" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href="http://github.com/cpett" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">GitHub</span></a>\r\n                                </li>\r\n                                <li>\r\n                                    <a href="https://github.com/doconix/django-mako-plus" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">DMP</span></a>\r\n                                </li>\r\n                            </ul>\r\n')
        __M_writer('                    </div>\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n        <!-- /.container -->\r\n\r\n    </div>\r\n    <!-- /.intro-header -->\r\n\r\n    <!-- Page Content -->\r\n\r\n    <a  name="services"></a>\r\n    <div class="content-section-a">\r\n\r\n        <div class="container">\r\n            <div class="row">\r\n                <div class="col-lg-5 col-sm-6">\r\n                    <hr class="section-heading-spacer">\r\n                    <div class="clearfix"></div>\r\n                    <h2 class="section-heading">A Bit About<br>This Site</h2>\r\n                    <p class="lead">I started building this site during my free time after an intro to web dev class. I wanted to practice more with <a href="https://github.com/doconix/django-mako-plus">Django-Mako-Plus</a> and <a href="http://d3js.org/">d3.js</a>.<br>\r\n                    If you want to look around, feel free to create a profile, or ask me for the test account credentials.<br>\r\n                    This is very much a work-in-progress, but feel free to poke around and please give me feed back!</p>\r\n                </div>\r\n                <div class="col-lg-5 col-lg-offset-2 col-sm-6">\r\n                    <img class="img-responsive" src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/ipad.png" alt="">\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n        <!-- /.container -->\r\n\r\n    </div>\r\n    <!-- /.content-section-a -->\r\n\r\n    <div class="content-section-b">\r\n\r\n        <div class="container">\r\n\r\n            <div class="row">\r\n                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">\r\n                    <hr class="section-heading-spacer">\r\n                    <div class="clearfix"></div>\r\n                    <h2 class="section-heading">A Bit About<br>Me</h2>\r\n                    <p class="lead">My name is Cody Pettit. I am currently working toward a Masters of Information Systems Management at BYU. I have a passion for technology, and I am fasinated by data security and the trends within that industry.<br><br>When I\'m not studying or working, I am probably working on projects like this, watching a movie with my beautiful wife, Sidney, or longboarding in the canyon with friends.<br><br>Sidney and I love to travel and have adventures! I lived in Romania for two years, and we have been to Jamaica, Grand Cayman, and Cozumel. We are planning a trip to Europe after we graduate--We want to see as much of the world as possible!<br><br>Please feel free to reach out to me via email or LinkedIn.</p>\r\n                </div>\r\n                <div class="col-lg-5 col-sm-pull-6  col-sm-6">\r\n                    <img class="img-responsive" src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/me.jpg" alt="">\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n        <!-- /.container -->\r\n\r\n    </div>\r\n    <!-- /.content-section-b -->\r\n\r\n    <div class="content-section-a">\r\n\r\n        <div class="container">\r\n\r\n            <div class="row">\r\n                <div class="col-lg-5 col-sm-6">\r\n                    <hr class="section-heading-spacer">\r\n                    <div class="clearfix"></div>\r\n                    <h2 class="section-heading">A Bit About<br>The Technology</h2>\r\n                    <p class="lead">I used <a href="https://github.com/doconix/django-mako-plus">Django-Mako-Plus</a> (DMP) to develop this site. The main purpose of this site was to practice with DMP and learn data visualization with <a href="http://d3js.org/">d3.js</a>. This site also features a PostegreSQL database, Bootstrap, and a few JavaScript libraries. Also, the stock photos are from <a href="http://deathtothestockphoto.com/">Death to the Stock Photo</a?</p>\r\n                </div>\r\n                <div class="col-lg-5 col-lg-offset-2 col-sm-6">\r\n                    <img class="img-responsive" src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/media/music.png" alt="">\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n        <!-- /.container -->\r\n\r\n    </div>\r\n    <!-- /.content-section-a -->\r\n\r\n    <a  name="contact"></a>\r\n    <div class="banner">\r\n\r\n        <div class="container">\r\n\r\n            <div class="row">\r\n                <div class="col-lg-6">\r\n                    <h2>Summer 2015 Project</h2>\r\n                </div>\r\n                <div class="col-lg-6">\r\n                    <ul class="list-inline banner-social-buttons">\r\n                        <li>\r\n                            <a href="https://github.com/doconix/django-mako-plus" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">DMP</span></a>\r\n                        </li>\r\n                        <li>\r\n                            <a href="https://github.com/cpett" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>\r\n                        </li>\r\n                        <li>\r\n                            <a href="https://www.linkedin.com/in/codybpettit" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>\r\n                        </li>\r\n                    </ul>\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n        <!-- /.container -->\r\n\r\n    </div>\r\n    <!-- /.banner -->\r\n\r\n    <!-- Footer -->\r\n    <footer>\r\n        <div class="container">\r\n            <div class="row">\r\n                <div class="col-lg-12">\r\n                    <ul class="list-inline">\r\n                        <li>\r\n                            <a href="#">Home</a>\r\n                        </li>\r\n                        <li class="footer-menu-divider">&sdot;</li>\r\n                        <li>\r\n                            <a href="#about">About</a>\r\n                        </li>\r\n                        <li class="footer-menu-divider">&sdot;</li>\r\n                        <li>\r\n                            <a href="#services">Services</a>\r\n                        </li>\r\n                        <li class="footer-menu-divider">&sdot;</li>\r\n                        <li>\r\n                            <a href="#contact">Contact</a>\r\n                        </li>\r\n                    </ul>\r\n                    <p class="copyright text-muted small">Est odio ac at nulla, litora proin aenean risus nulla soluta</p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </footer>\r\n\r\n    <!-- jQuery \r\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/scripts/jquery.js"></script>\r\n    -->     \r\n    <!-- Bootstrap Core JavaScript -->\r\n    <script src="')
        __M_writer(str( STATIC_URL ))
        __M_writer('homepage/scripts/bootstrap.min.js"></script>\r\n\r\n</body>\r\n\r\n</html>\r\n')
        return ''
    finally:
        context.caller_stack._pop_frame()


"""
__M_BEGIN_METADATA
{"source_encoding": "utf-8", "filename": "C:\\Python34\\Lib\\site-packages\\django\\bin\\summer_project/homepage/templates/base2.htm", "uri": "/homepage/templates/base2.htm", "line_map": {"17": 4, "19": 0, "27": 2, "28": 4, "29": 5, "33": 5, "34": 23, "35": 28, "36": 28, "37": 29, "38": 29, "39": 30, "40": 30, "41": 31, "42": 31, "43": 32, "44": 32, "45": 34, "46": 34, "47": 37, "48": 37, "49": 40, "50": 40, "51": 51, "52": 51, "53": 51, "54": 73, "55": 74, "56": 78, "57": 79, "58": 84, "59": 86, "60": 87, "61": 87, "62": 87, "63": 98, "64": 139, "65": 140, "66": 154, "67": 155, "68": 166, "69": 167, "70": 179, "71": 205, "72": 205, "73": 227, "74": 227, "75": 249, "76": 249, "77": 318, "78": 318, "79": 321, "80": 321, "86": 80}}
__M_END_METADATA
"""
